randomizeNPT<-function(DIR="",DSN="",File=""){
  #' Remove any objects in the workspace
  rm(list = ls(all.names = TRUE))    
  #' remove verbose warnings
  options(warn=-1)		
  
  #' **************************************************************************#
  #' ********************* Manually updated section ***************************#
  #' PART I: Obtain working directory containing the Excel file 
  #' Ensure that for entries>12 generate the randomization files using ALPHA
  #' program and copy them in this directory
  #' @export
  
  DIR<-'D:/Flash2/2015'
  
  #' The names pointing to the DSN files generated by 
  #' ALPHA pogram (if entries are more than 12). Ensure you input the suffix
  #' Example 'A001.dsn' is 'A', MEET001.dsn' is 'MEET'
  DSN<-'STEL'
  
  #' The name of the Excel file that has both 'ENT' and 'SITES' sheets
  xel<-'KARI NJORO SWEET POTATO 2015 DATA - Copy'  
  #' ********************** End of manually updated files **********************#
  #' ***************************************************************************#
  
  if(DIR=="" | xel=="") stop("The directory and/or SITE/ENT file is not provided")
  
  if(DIR!="" & xel!="") {	
    #' PART II: Read files both the entries (ENT) and SITES sheets
    #' The sheet files must have EXP_NAME
    SITES<-XLConnect::readWorksheet(loadWorkbook(paste0(DIR,'/',xel,'.xls' )),sheet="SITES",header=T)
    E<-XLConnect::readWorksheet(loadWorkbook(paste0(DIR,'/',xel,'.xls')),sheet="ENT",header=T);
    
    #' Determine the number of sites
    sn<-length(SITES$SITE)
    
    #' Generate entry numbers if they are not already there
    if(length('ENTRY' %in% colnames(E))==0 | length(unique(E$ENTRY))< length(unique(E$EXP_NAME))){
      E$ENTRY<-sample(length(as.character(E$EXP_NAME)))
      E$ENTRY<-as.numeric(as.character(E$ENTRY))
    }
    
    #' PART III: GENERATE APPROPRIATE DESIGN
    #' 1. RCBD DESIGN
    if(length(as.character(E$EXP_NAME))<13){
      
      for(i in 1:sn){
        #' Note that 
        a<-agricolae::design.rcbd(c(1:length(E$EXP_NAME)),r=3,serie = 0,
                                  seed=i,kinds = "Super-Duper", first=T)
        a<-a$book
        a<-a[order(a$plots),]
        a$plots<-c(1:length(a$plots))
        a<-cbind(i,a);
        a<-reshape::rename(a,c(i='SITENO',block='REP',plots='PLOT',
                               'c(1:length(E$EXP_NAME))'='ENTRY'))
        a$ENTRY<-as.numeric(as.character(a$ENTRY))
        a$REP<-as.numeric(as.character(a$REP))
        ifelse(i==1,A<-a,A<-rbind(A,a))
      }
      #' END OF RCBD
    }
    
    #' 2. IBD DESIGN
    if(length(as.character(E$EXP_NAME))>12){
      #' Check if the ALPHA files have been generated
      
      if(length(dir(path=DIR, pattern = ".DSN", ignore.case = TRUE))<sn){
        print(paste("Error: the program stopped running Ensure that you have at least:",sn, 
                    ".DSN files generated from ALPHA program"))
      }
      if(length(dir(path=DIR, pattern = ".DSN", ignore.case = TRUE))>=sn){
        for(i in 1:sn){
          z<-ifelse(i<10,"00",ifelse(i<100,"0",as.character(i)))
          d<-paste0(DIR,DSN,z,i,'.dsn')
          a<-read.table(d,header=F)
          a<-cbind(i,a);
          a<-reshape::rename(a,c(i='SITENO',V1='REP',V2='BLOC',V3='P',V4='ENTRY'))
          a$ENTRY<-as.numeric(as.character(a$ENTRY))
          a$REP<-as.numeric(as.character(a$REP)) 
          a<-a[order(a$P),]
          #Re-randomize within blocks to avoided repeated entries
          a$R<-sample(length(a$REP))
          a<-a[order(a$REP,a$BLOC,a$R),]
          a$PLOT<-c(1:length(a$REP))
          a$R<-NULL;a$P<-NULL;
          ifelse(i==1,A<-a,A<-rbind(A,a))
        }
      }
      #'END OF IBD
    }
    
    #' PART IV: MERGE DESIGN, ENTRIES AND SITES AND FORMAT RESPECTIVELY
    A<-merge(A,E,by='ENTRY');
    A<-merge(A,SITES,by='SITENO');
    
    #' Create Labeling dataset TRANSPOSE THE DATA LABELS and rename accordingly
    LABEL<-subset(A,select=c(ENTRY, EXP_NAME, SITENO,SITE,REP,PLOT))
    LABEL<-LABEL[order(LABEL$REP,LABEL$EXP_NAME,LABEL$SITE),]
    LABEL<-reshape(LABEL, timevar = "REP",
                   idvar = c('ENTRY', 'EXP_NAME', 'SITENO','SITE'),direction='wide'
    )
    LABEL<-reshape::rename(LABEL,c(PLOT.1='REP1', PLOT.2='REP2', PLOT.3='REP3'))
    LABEL<-LABEL[order(LABEL$EXP_NAME),]
    
    ifelse(length(as.character(E$EXP_NAME))<13,
           A1<-subset(A,
                      select=c(REGION,SITENO,SITE,PLOT,REP,ENTRY,EXP_NAME,SOURCE,TEST.STATUS)),
           A1<-subset(A,
                      select=c(REGION,SITENO,SITE,PLOT,REP,BLOC,ENTRY,EXP_NAME,SOURCE,TEST.STATUS))
    )
    
    A1<-A1[order(A1$REGION,A1$SITE,A1$PLOT),]
    
    #' PART V: EXPORT TO THE RESPECTIVE EXCEL FILE
    #' WRITE XLS FILES in different sheets replacing
    wb <- XLConnect::loadWorkbook(paste0(DIR,"/",xel,".xls"), create=T)
    XLConnect::createSheet(wb, name = "RANDOM")
    XLConnect::createSheet(wb, name = "ENT1")
    XLConnect::createSheet(wb, name = "DAT")
    XLConnect::createSheet(wb, name = "LABEL")
    XLConnect::writeWorksheet(wb, A, sheet="RANDOM")
    XLConnect::writeWorksheet(wb, E, sheet="ENT1")
    XLConnect::writeWorksheet(wb, LABEL, sheet="LABEL")
    XLConnect::writeWorksheet(wb, A1, sheet="DAT")
    XLConnect::saveWorkbook(wb) 
  }	
}